### ISSUE TITLE
Freezes just before fighting Goro

### ISSUE THREAD

**Issue by deadlygroove** [jvisser/msu-md-mk1#1]
Hi, thank you for creating this hack. I appreciate your effort. I just wanted to let you know that in testing this on the Mega Everdrive Pro, MegaSD and the MiSTer it locks up just before fighting Goro. You might already be aware of this but I just wanted to let you know just in case you didn't. Thank you for your work! :)

**Comment by jvisser** [comment]
Hi @deadlygroove,

Thanks for reporting. I may have fixed it. I made a mistake due to my unfamiliarity with VASM causing the patch to overwrite game code. I made a new release with the fix.

Can you test it and report back if it works? Thanks!

**Comment by deadlygroove** [comment]
Hiya jvisser, so I tested it on all 3 devices and it still locks up after the 3rd endurance match just before Goro comes in. I tried beating the match ending with Fatalities and without Fatalities and the same thing. It just locks up. I just thought I would let you know and thanks again. I wish I could help you figure it out but I don't know anything about creating msu-md or MD+ patches. I can only do the soundpacks. I have a great deal of respect for you guys and what you bring to the community. :)

**Comment by jvisser** [comment]
Hi @deadlygroove , I made a new release that should fix the crash when Goro appears. Also track 18 is now mapped to Game Over.

btw thanks for the kind words :) I feel the same about soundpack creators like yourself :) We're part of the same team I guess, without soundpack creators there would be not much use for these patches.

**Comment by deadlygroove** [comment]
Hey jvisser, I just tested it on all 3 devices and it works nicely dude. I added in track 18 for the soundpacks. I can't express how much I really appreciate your time with this. It would be cool be able to add in the sound for fatalities but I understand if that's not possible. I'm already grateful for the state that this patch is in. Anyway appreciate you and thank you very much. :)

**Comment by jvisser** [comment]
Hi @deadlygroove, I didnt realize yesterday, maybe you are not aware of this but the patch is still in development over at the zeldix forums. Relikk over there is making a soundpack. I already added some more tracks including a fatality track as I posted in the dev thread over there.

Where is your soundpack hosted?

I released it on GitHub as a 1.0 release too soon  (first version was rushed due to time constraints). Making it look finished. Not realizing then people would find it so quickly outside of zeldix.

**Comment by deadlygroove** [comment]
Hi jvisser, I'm reading the thread right now. That's great that Relikk is making a soundpack. I'm not hosting mine atm because of current changes but I may host them on my drive and if zeldix will allow me. I don't know if I joined that forum. If not I'll have to sign up.
