### ISSUE TITLE
HELP, PLEASE READ BELOW

### ISSUE THREAD

**Issue by independence106** [jvisser/msu-md-mk1#2]
First, sorry if this seems weird, I couldn't find another way to contact you.

You've submitted pull requests for TiledReader and I was wondering if you could help me a bit with using it, or if there is any CLEAR documentation. 

I already asked Andrew, and he referred me to the people who made pull requests.

Thanks a lot.

P.S, plz respond

**Comment by jvisser** [comment]
Not sure who Andrew is... But you should check the original repo by Alex Heyman. https://github.com/AlexHeyman/TiledReader. It has JavaDoc also the author has some other projects using it I think. There is no getting started guide as far as I know.
