### ISSUE TITLE
Back #2, I just need 1 piece of information

### ISSUE THREAD

**Issue by independence106** [jvisser/msu-md-mk1#3]
I read the javadocs, but one issue I didn't find out was how I can draw the TiledTile on my canvas, since canvas can only draw Images not TiledImages, and I can't cast it.

P.S, sorry, It was Alex who referred me to you!

**Comment by jvisser** [comment]
Not sure why Alex refered you to me, I don't know anything about what you are asking. Anyway...

There is a lib included with Tiled that does rendering for you iirc https://github.com/mapeditor/tiled/tree/master/util/java/libtiled-java. Maybe use that instead.

You could also just export the map to PNG and use that.

With TiledReader it seems pretty straightforward to me. Looking at the classes, probably use TiledTile.getTilesetX/Y and TiledTile.getImage to get to the source image. 

For the actual rendering I suggest you check stackoverflow or some basic Java tutorial. 
For question about the Tiled editor check their forum of discord. 
But most importantly: Use your favorite search engine, pretty sure it has answers to your questions ;).

I'm sure you can figure this out!

Please don't open any more issues on this repo, except if it's about the actual software in the repo.
